spring:
  application:
    name: catalog

  lifecycle:
    timeout-per-shutdown-phase: 1m

  datasource:
    url: jdbc:postgresql://localhost:5432/bookz-catalog
    username: root
    password: root

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true




server:
  port: 8181
  shutdown: graceful
